baseURL = "https://alternative-rvb.github.io/hugo-basic/"
title = "My New Hugo Site"
theme = "basic-theme"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20
